services:
  database:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db-boticario"
    ports:
      - "5432:5432"
