services:
  database:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db-boticario"
    ports:
      - "5432:5432"
    networks:
      - app_network

  api:
    build: .
    environment:
      PORT: "3001"
      DB_CONNECION_URL: "postgres://postgres:postgres@database:5432/db-boticario"
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
